/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "I2C_Read_Ext_Device.h"
#include "Bsp.h"
#include <Driver_Can1.h>
#include "IfxGpt12.h"
#include "IfxCpu_Irq.h"

#define TEST_PIN                 &MODULE_P00,6

union
{
    uint16 data;
    uint8 a[2];
} output;

uint16 outputdata ;
int flag = 0;
int output_data = 0;
extern int mode_select;

IfxCpu_syncEvent g_cpuSyncEvent = 0;
IfxMultican_Message   RX_Msg;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    Driver_Can_Init();
    MOTOR_ENABLE_INIT();
    MOTOR_ENABLE1();

    /* Initialize the I2C module and read the MAC address of the external device */
    init_I2C_module();
    //read_ext_device_address();
    IfxPort_setPinMode(TEST_PIN , IfxPort_Mode_outputPushPullGeneral);

    while(1)
    {

        if(flag == 0){
        read_ext_device_address();
        IfxPort_setPinState(TEST_PIN , IfxPort_State_low);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 5));
        IfxPort_setPinState(TEST_PIN , IfxPort_State_high);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 5));
//        rx_buff();
        flag=1;
        }
        else if(flag==1) {
                outputdata = rx_buff();
                output.data = outputdata;
                if(mode_select == 1)
                {
                    MOTOR_MODE_VEL();
                    CAN_TEST_Vel(output.a[0],output.a[1]);
                }
                else
                {
                    MOTOR_MODE_POS();
                    CAN_TEST_Pos(output.a[0],output.a[1]);
                }
                flag=0;

        }
    }
    return (1);
}
